---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 13

platforms:
  - name: ubuntu-16.04

suites:
  - name: install_only
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::install_binary]
    attributes:
      authorization: 
        sudo: 
          users:
            - vagrant
      apt:
        compile_time_update: true
      consul:
        config:
          bootstrap_expect: 1
          server: true
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    attributes:
      authorization: 
        sudo: 
          users:
            - vagrant
      apt:
        compile_time_update: true
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        config:
          consul: '127.0.0.1:8500'
  - name: runit
    run_list:
      - recipe[apt::default]
      - recipe[consul::default]
      - recipe[consul-template::default]
      - recipe[consul-template-spec::consul_template_config]
    attributes:
      authorization: 
        sudo: 
          users:
            - vagrant
      apt:
        compile_time_update: true
      consul:
        config:
          bootstrap_expect: 1
          server: true
      consul_template:
        init_style: 'runit'
        config:
          consul: '127.0.0.1:8500'